<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'kornrunner\\' => array($vendorDir . '/kornrunner/keccak/src'),
    'Web3p\\RLP\\' => array($vendorDir . '/web3p/rlp/src'),
    'Web3p\\EthereumUtil\\' => array($vendorDir . '/web3p/ethereum-util/src'),
    'Web3p\\EthereumTx\\' => array($vendorDir . '/web3p/ethereum-tx/src'),
    'Web3\\' => array($vendorDir . '/sc0vu/web3.php/src'),
    'Slim\\Views\\' => array($vendorDir . '/slim/php-view/src'),
    'Slim\\' => array($vendorDir . '/slim/slim/Slim'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Interop\\Container\\' => array($vendorDir . '/container-interop/container-interop/src/Interop/Container'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'EthTool\\' => array($baseDir . '/ethtool/src'),
    'Elliptic\\' => array($vendorDir . '/simplito/elliptic-php/lib'),
    'BN\\' => array($vendorDir . '/simplito/bn-php/lib'),
    'BI\\' => array($vendorDir . '/simplito/bigint-wrapper-php/lib'),
);
