sudo: required

language: php

php:
  - 7.1
  - 7.2

install:
  - composer install

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t d2ad6fff-f9bb-452b-a25c-1e13cdd81270